[project]
name = "inspect-cot-monitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "inspect-ai>=0.3.123",
    "openai>=1.101.0",
]
